'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=hostequal1.ddns.net;Initial Catalog=C:\USERS\AKUAKU\DOWNLOADS\1_9_EQU"& _ 
            "AL\EQUALV1_24_7\EQUALV1_16_7\EQUALV1\EQUALV1\DATABASE1.MDF;User ID=SuperAdmin;Pa"& _ 
            "ssword=SuperAdmin")>  _
        Public ReadOnly Property equalPoint() As String
            Get
                Return CType(Me("equalPoint"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=hostequal1.ddns.net;Initial Catalog=C:\USERS\AKUAKU\DOWNLOADS\1_9_EQU"& _ 
            "AL\EQUALV1_24_7\EQUALV1_16_7\EQUALV1\EQUALV1\DATABASE1.MDF;Persist Security Info"& _ 
            "=True;User ID=SuperAdmin;Password=SuperAdmin")>  _
        Public ReadOnly Property C__USERS_AKUAKU_DOWNLOADS_1_9_EQUAL_EQUALV1_24_7_EQUALV1_16_7_EQUALV1_EQUALV1_DATABASE1_MDFConnectionString() As String
            Get
                Return CType(Me("C__USERS_AKUAKU_DOWNLOADS_1_9_EQUAL_EQUALV1_24_7_EQUALV1_16_7_EQUALV1_EQUALV1_DAT"& _ 
                    "ABASE1_MDFConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PointOfSaleALPHA.My.MySettings
            Get
                Return Global.PointOfSaleALPHA.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
